### ISSUE TITLE
5. Add social image and description for node.js site

### ISSUE THREAD

**Issue by kahlie-huff** [thisdot/framework.dev#381]
# Add framework social image and description for the node.js framework.dev site.

## Background

As an user I would like to have the possibility to share the site on social media and for it to have a nice image and description defined, so that it will increase its visibility and shareability

## Acceptance

- [x] Add metadata description
- [x] Add social image
- [ ] Test the site on "https://socialsharepreview.com/"

## Instructions
Designers provided instructions on how to create the images based on a template in Figma. You can find a tutorial video below along with links to the relevant sections in Figma. Let me know if you are missing access and we'll get it for you.

[Loom tutorial](https://www.loom.com/share/8d703c1eb2e548af96ceb6f09d028485)
[Open graph image](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2725%3A130781)
[Hero Graphic](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2731%3A128595)
[Logos](https://www.figma.com/file/kbSN3VYmIzdjQEx5mbBTSs/Framework-Dev?node-id=2732%3A129089)
[Color seeds to build a theme](https://www.figma.com/file/3cAQKdlEpCrz7dgeKzJEqQ/Framework-library?node-id=9276%3A22559)

**Comment by jnalei** [comment]
This issue is addressed in Morgan's PR #360

**Comment by morgnism** [comment]
@jnalei we can wait to close this once my PR's merged and verified to be working correctly.

**Comment by morgnism** [comment]
**Facebook and LinkedIn**
![Image](https://user-images.githubusercontent.com/9042219/199601049-f3a248d0-ca71-4cb8-9682-568e2829aade.png)

**Twitter**
Still broken

**Comment by morgnism** [comment]
The validator still says that there isn't an image, but because the `og:image` fallback works, this is passable.


![Image](https://user-images.githubusercontent.com/9042219/199617697-f2a1b137-db7c-49c5-bdab-6a17f10608a9.png)
